### ISSUE TITLE
Crash when Indexing Larger Folders

### ISSUE THREAD

**Issue by lluuaapp** [grosjo/fts-xapian#2]
The indexer process crashes reproducible with the following command after about 2000 messages were indexed:

doveadm index -u paul@iwascoding.com -q \*

Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Effective uid=8, gid=8, home=/var/spool/mail/iwascoding/paul
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Quota root: name=User quota backend=dict args=:file:/var/spool/mail/iwascoding/paul/dovecot-quota
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Quota rule: root=User quota mailbox=* bytes=2147483648 messages=0
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Quota rule: root=User quota mailbox=* bytes=2147483648 messages=60000
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Quota grace: root=User quota bytes=214748364 (10%)
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: dict quota: user=paul@iwascoding.com, uri=file:/var/spool/mail/iwascoding/paul/dovecot-quota, noenforcing=0
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Namespace inbox: type=private, prefix=, sep=/, inbox=yes, hidden=no, list=yes, subscriptions=yes location=mdbox:~/mdbox
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: fs: root=/var/spool/mail/iwascoding/paul/mdbox, index=, indexpvt=, control=, inbox=, alt=
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: FTS Xapian: Partial=2, Full=20 DB_PATH=/var/spool/mail/iwascoding/paul/mdbox/xapian-indexes
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: quota: quota_over_flag check: quota_over_script unset - skipping
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Mailbox sent: Mailbox opened because: indexing
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: FTS Xapian : Mailbox sent : Last UID=0
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: FTS Xapian : Mailbox sent : Last UID=0
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Namespace : Using permissions from /var/spool/mail/iwascoding/paul/mdbox: mode=0700 gid=default
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Mailbox sent: UID 1: Opened mail because: fts indexing
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Opening RW /var/spool/mail/iwascoding/paul/mdbox/xapian-indexes/db_9ddfe10d8a8a8a568c120000654d370e
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Mailbox sent: UID 2: Opened mail because: fts indexing
Jan 14 09:26:08 mail dovecot: indexer-worker(paul@iwascoding.com)<16777><IKpfOqBHPFyJQQAADYqDFA>: Debug: Mailbox sent: UID 3: Opened mail because: fts indexing

I tried to delete the message, but this does not help (crashes e.g. after message 2029 or 2044). Other folders with fewer messages were successfully indexed before.

**Comment by grosjo** [comment]
Source probleme is not linked to the numebr of emails (my mailboxes are 40k or more emails, without any trouble)
I am looking into this

Don't hesitate to reinstall the pluging with the recent updates and try again with the same mailbox

**Comment by grosjo** [comment]
I added a log on the terms added to the index (see below)

Please rerun with the lastest version of the code and let me know the log at the momoent of the crash

Jan 14 20:51:45 gjserver dovecot[17034]: indexer-worker(jom@grosjo.net)<17049><P2FQCWH2PFzqRgAA0thIag:wPjnLGH2PFyZQgAA0thIag>: Warning: Index message-id : 207 terms, maxlength: 38
Jan 14 20:51:45 gjserver dovecot[17034]: indexer-worker(jom@grosjo.net)<17049><P2FQCWH2PFzqRgAA0thIag:wPjnLGH2PFyZQgAA0thIag>: Warning: Index from : 221 terms, maxlength: 22
Jan 14 20:51:45 gjserver dovecot[17034]: indexer-worker(jom@grosjo.net)<17049><P2FQCWH2PFzqRgAA0thIag:wPjnLGH2PFyZQgAA0thIag>: Warning: Index to : 229 terms, maxlength: 20

**Comment by lluuaapp** [comment]
This still crashes. And the message is not always the same (looked it up in the stack trace/code dump). 

Here is log from the current source:

Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index message-id : 281 terms, maxlength: 75
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index message-id : 84 terms, maxlength: 10
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index to : 103 terms, maxlength: 15
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index from : 105 terms, maxlength: 18
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index from : 248 terms, maxlength: 20
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index to : 129 terms, maxlength: 19
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index message-id : 230 terms, maxlength: 47
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index from : 248 terms, maxlength: 20
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index to : 129 terms, maxlength: 19
Jan 14 21:56:34 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Warning: Index message-id : 212 terms, maxlength: 50
Jan 14 21:56:34 mail dovecot: indexer-worker: Error: terminate called after throwing an instance of 'std::bad_alloc'
Jan 14 21:56:34 mail dovecot: indexer-worker: Error:   what():  std::bad_alloc
Jan 14 21:56:34 mail dovecot: indexer: Error: Indexer worker disconnected, discarding 31 requests for paul@iwascoding.com
Jan 14 21:56:35 mail dovecot: indexer-worker(paul@iwascoding.com)<8124><0FeLM3v3PFy8HwAADYqDFA>: Fatal: master: service(indexer-worker): child 8124 killed with signal 6 (core dumped)

**Comment by grosjo** [comment]
Can you add the gdb backtrace of this coredump ?

**Comment by lluuaapp** [comment]
This is really strange. After your recent changes, I do not get the exception at the call add_term(), now I get one at replace_document() in fts_backend_xapian_index_text():

[bt.txt](https://github.com/grosjo/fts-xapian/files/2758738/bt.txt)

**Comment by lluuaapp** [comment]
I added some additional catches here and there (and also catch the std::bad_alloc) but the exceptions then just get thrown elsewhere. Seems the whole Xapian lib relies heavily on these exceptions. And it seems a more memory-related problem. Do you have UTF8/international characters in your mailboxes?

Maybe its something with my setup? mdbox? libxapian v1.4.3-2+deb9u2?

Attached is a stack trace and a diff with my last catch-changes.

[fts-backend-xapian-functions.patch.txt](https://github.com/grosjo/fts-xapian/files/2759014/fts-backend-xapian-functions.patch.txt)
[bt.txt](https://github.com/grosjo/fts-xapian/files/2759015/bt.txt)

**Comment by grosjo** [comment]
It looks very much like a problem in your version of Xapian.
Latest is 1.4.9 and the one available in ArchLinux for instance. Debian is 
always late in updating library, but is there a way for you to try with 1.4.9 ?

I am also using mdbox

Yes, plenty of chinese/hebrew emails

**Comment by lluuaapp** [comment]
Sorry, still no success. But as the backport of Xapian 1.4.9 does not include a dbg version I do not have  symbols for the lib. Still crashing in fts_backend_xapian_index_hdr().

**Comment by grosjo** [comment]
I have no crash whatsoever since Sunday , indexing my 120G of emails and running on incoming emails. And the bug seems coming from add_term of the Xapian lib. 

Can you forward me an email (to jom@grosjo.net) that make your server crash ?

**Comment by grosjo** [comment]
Please kindly try again with recent cleanup

**Comment by lluuaapp** [comment]
It seems I found what is causing the crash:

```
# Default VSZ (virtual memory size) limit for service processes. This is mainly
# intended to catch and kill processes that leak memory before they eat up
# everything.
default_vsz_limit = 2048M
```

This value for default_vsz_limit fixed it for me. It was not set (256M seems to be the default) so it was Dovecot's main process killing the indexer-worker process?

**Comment by grosjo** [comment]
yes, it is ture that the xapian eats a lot of memory.  

Let's see if the crash happens again or not after few days or not, to
confirm

**Comment by grosjo** [comment]
I updated the README accordingly. Thanks a lot

**Comment by lluuaapp** [comment]
You can also set the limit only for the indexer:

```
service indexer-worker {
  # this is for fts-xapian
  vsz_limit = 2G
}
```

**Comment by grosjo** [comment]
Any further crash ?

**Comment by lluuaapp** [comment]
The latest release crashes immediately. Seems that you are double-freeing some allocated memory? This is the log:

Jan 19 18:11:29 mail dovecot: indexer-worker: Error: *** Error in `dovecot/indexer-worker': corrupted size vs. prev_size: 0x000055dea5dacad0 ***

I have to go back to "BETA3" commit, maybe its the allocation in "Clarify hte installation testing"?

[bt.txt](https://github.com/grosjo/fts-xapian/files/2775785/bt.txt)

**Comment by grosjo** [comment]
Please to install the very latest git, and post the bt, together with
the dovecot log file at the time of crash 

thx

**Comment by lluuaapp** [comment]
Here is what you asked for:

[bt.txt](https://github.com/grosjo/fts-xapian/files/2775820/bt.txt)

**Comment by grosjo** [comment]
This is very weird because line 567 is nothing. 

Are you sure there are no 2 dovecot running ? 

I added some debug around this line. 

Can you try again ?

**Comment by lluuaapp** [comment]
You are right. I forgot to remove some tests I did to prevent this crash. Here are the right data:

[bt.txt](https://github.com/grosjo/fts-xapian/files/2775874/bt.txt)

**Comment by grosjo** [comment]
can you try increasing default_vsz_limit  ?

**Comment by grosjo** [comment]
When I re-index my own INBOX, I see 3.6G used for indexing 192 819
emails 

23096 mailuse+ 20 0 3846.7m 3.6g 2.0 5.7 6:49.64 D
dovecot/indexer-worker [jom@grosjo.net INBOX - 55400/192819]

**Comment by grosjo** [comment]
the code is comminting changes from memory to disk every 10 000 entries
(1 entry = 1 field of email (To, CC, ...) , to speedup the indexing. 

maybe put much lower value in 

#define XAPIAN_COMMIT_LIMIT 10000 

(maybe 100 ?)

**Comment by lluuaapp** [comment]
Even with XAPIAN_COMMIT_LIMIT == 100 and default_vsz_limit 8GB it crashes immediately. I do not think that in this short amount of time the 8GB could not be allocated.

Currently I have no clue what can cause the crash. What puzzles me is that commit 97d0a5d18210f2019f16b448e94d055b9c1cb63d works perfectly fine :-(

**Comment by grosjo** [comment]
and I can not manage to repeat your error;

The real difference after 97d05d , is the regular commit on disk 
I added a "close()"  before freeing the ressource that open the indexes in read Only, where your error happens.
Can you try again ?

**Comment by lluuaapp** [comment]
Still crashes immediately, but in a totally different part and with a different error (free(): invalid pointer):

[bt.txt](https://github.com/grosjo/fts-xapian/files/2775936/bt.txt)

Maybe there is a ownership-change in the memory you are allocating? Did you think to only use i_malloc/i_free? But I am just guessing...

**Comment by grosjo** [comment]
Hi
I replaced the free() by i_free, to remove that doubt

**Comment by grosjo** [comment]
I also fixed a memory leak. That was maybe the root cause

**Comment by grosjo** [comment]
Reindexing my own mailbox gets it from above 3G down to 200m
So maybe a good fix.

Can you try again ? crossing fingers ;)

**Comment by lluuaapp** [comment]
Sorry to say, but this does not fix the crash. It still crashes immediately without any further logging. I think there is a double-free somewhere in the code (free(): invalid pointer error). Strangely the crash moved from the plugin (new WritableDatabase) to general dovecot code (mailbox_free/mail_thread_mailbox_free) with you last changes. What is strange too is that it does not crash for all accounts on my machine.

Maybe I find some time tomorrow and do some more debugging. Currently I am at the end of my ideas, but maybe slowly adding/removing your changes one by one discovers the root cause.

In my opinion the change from stack to heap memory (char path[1000]; -> char * path;, commit 03ef01561cca0d884c3bdc7af05a9930915ac200) introduced the crash. Somewhere the ownership for either the path or the db memory changed and someone else thinks it must be freed a second time.

I also added a NULL assignment to all cases where the memory is freed in the plugin (to skip another free) but to no avail.

I am not that familiar with what is called when in the plugin-code so I need some more time to get new ideas and try out/debug some more.

**Comment by grosjo** [comment]
I can not repeat your bug. The difference maybe the version of Dovecot.

Maybe can you try with dovecot git ?

**Comment by lluuaapp** [comment]
See my PR. This fixes the crash. It was just a simple calculation wrong for the length of the db string. This did not crash on the first sprintf but later when the c++ string was created.

https://github.com/grosjo/fts-xapian/pull/7

**Comment by grosjo** [comment]
Great. Thank you so much
